{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata": {
    "name": {{ .Release.Name | quote }},
    "labels": {{ include "agentregistry-operator.labels" . }},
    "namespace": {{ .Release.Namespace | quote }}
  },
  "automountServiceAccountToken": false
}
