{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": {{ .Release.Name | quote }},
    "labels": {{ include "agentregistry-operator.labels" . }},
    "namespace": {{ .Release.Namespace | quote }}
  },
  "spec": {
    "type": "ClusterIP",
    "selector": {
      "app.kubernetes.io/name": "agentregistry-operator",
      "app.kubernetes.io/instance": {{ .Release.Name | quote }}
    },
    "ports": [
      {
        "name": "http",
        "port": 8080,
        "targetPort": "http"
      }
    ]
  }
}
